brain_two/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("todos/", include("todos.urls")), #configs path to Django app todos we created, and accesses the urls.py file
]

todos/urls.py
from django.urls import path

from todos.views import (
    TodoListListView,
    TodoListDetailView,
    TodoListCreateView,
    TodoListUpdateView,
    TodoListDeleteView,
    TodoItemCreateView,
    TodoItemUpdateView,
)

urlpatterns = [
    path("", TodoListListView.as_view(), name = "todo_list_list"),
    path("<int:pk>/", TodoListDetailView.as_view(), name = "todo_list_detail"),
    path("create/", TodoListCreateView.as_view(), name = "todo_list_create"),
    path("<int:pk>/edit/", TodoListUpdateView.as_view(), name = "todo_list_update"),
    path("<int:pk>/delete/", TodoListDeleteView.as_view(), name = "todo_list_delete"),
    path("items/create/", TodoItemCreateView.as_view(), name = "todo_item_create"),
    path("items/<int:pk>/edit/", TodoItemUpdateView.as_view(), name = "todo_item_update")
]

todos/models.py
from django.db import models

# Create your models here.
class TodoList(models.Model):
    name = models.CharField(max_length = 100)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name



class TodoItem(models.Model):
    task = models.CharField(max_length = 100)
    due_date = models.DateTimeField(blank = True, null = True)
    is_completed = models.BooleanField(default = False)
    list = models.ForeignKey(
        "TodoList", related_name = "items", on_delete = models.CASCADE, 
    )

    def __str__(self):
        return self.task

todos/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from todos.models import TodoItem, TodoList


# Create your views here.
class TodoListListView(ListView):
    model = TodoList
    template_name = "todo_lists/list.html"

class TodoListDetailView(DetailView):
    model = TodoList
    template_name = "todo_lists/detail.html"

class TodoListCreateView(CreateView):
    model = TodoList
    template_name = "todo_lists/create.html"
    fields = ["name"]


    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.id])

class TodoListUpdateView(UpdateView):
    model = TodoList
    template_name = "todo_lists/update.html"
    fields = ["name"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.id])

class TodoListDeleteView(DeleteView):
    model = TodoList
    template_name = "todo_lists/delete.html"
    success_url = reverse_lazy("todo_list_list")




class TodoItemCreateView(CreateView):
    model = TodoItem
    template_name = "todo_items/create.html"
    fields = ["due_date", "task", "is_completed", "list"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.list.id])

class TodoItemUpdateView(UpdateView):
    model = TodoItem
    template_name = "todo_items/update.html"

todos/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo Lists</title>
</head>

<body>
    {% block content %}
    {% endblock content %}    
</body>

</html>

todos/templates/todo_items/create.html
{% extends 'base.html' %}

{% block content %}
<main>
    <form method = "post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Complete</button>
    </form>
</main>
{% endblock content %}

todos/templates/todo_lists/create.html
{% extends 'base.html' %}

{% block content %}
<main>
    <form method = "post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="control">
            <button class="button">Submit</button>
        </div>
    </form>
</main>
{% endblock content %}

todos/templates/todo_lists/delete.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div class = "delete-form">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div>
                <button class="button">Delete</button>
            </div>
        </form>
    </div>
</main>
{% endblock content %}

todos/templates/todo_lists/detail.html
{% extends 'base.html' %}

{% block content %}
<main>
    <a href="{% url 'todo_list_list' %}">Back to list</a>
    <a href="{% url 'todo_list_update' todolist.id %}">Edit</a>
    <a href="{% url 'todo_list_delete' todolist.id %}">Delete</a>
    <h1>{{ todolist.name }}</h1>
    <h2>Tasks</h2>
    <table>
        <thead>
            <tr>
                <th>Task</th>
                <th>Due Date</th>
            </tr>
        </thead>
        <tbody>
            {% for item in todolist.items.all %}
                <tr>
                    <td><a href="{% url 'todo_item_update' item.id %}">{{ item.task }}</a></td>
                    <td>{{ item.due_date|date:"M d, Y"}}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</main>
{% endblock content %}

todos/templates/todo_lists/list.html
{% extends 'base.html' %}

{% block content %}
<main>
    <h1>My lists</h1>
    <a href="{% url 'todo_list_create' %}">Create a new list</a>
    <a href="{% url 'todo_item_create' %}">Create a new item</a>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Number of items</th>
        </tr>
    </thead>
    <tbody>
        {% for list in todolist_list %}
            <tr>
                <td><a href="{% url 'todo_list_detail' list.id %}">{{ list.name }}</a></td>
                <td>{{ list.items.all|length }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
</main>
{% endblock content %}

todos/templates/todo_lists/update.html
{% extends 'base.html' %}

{% block content %}
<main>
    <form method = "post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Complete</button>
    </form>
</main>
{% endblock content %}